apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-python
  template:
    metadata:
      labels:
        app: backend-python
    spec:
      containers:
        - name: backend-python
          image: sujalsharma/python-backend:v1
          ports:
            - containerPort: 5000