apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-node
  template:
    metadata:
      labels:
        app: backend-node
    spec:
      containers:
        - name: backend-node
          image: sujalsharma/node-backend:1.0
          ports:
            - containerPort: 3000